### ISSUE TITLE
Add to Readme

### ISSUE THREAD

**Issue by dderjoel** [mh21/i3-renameworkspaces#3]
Hi thanks for the script, but I had some issues with getting it to work. 
You might want to consider to add some info into the Readme:

1. Dependency of  `liblinux-inotify2-perl` which is availabe on Debian via `sudo apt install liblinux-inotify2-perl`
2. Configuration Keys are case sensitive.
3. Configuration Values support Fontawesome chars and styling as in the docu: e.g.: 
"<span foreground='teal'>Terminal </span>"
4. When using the switch-to-workspace feature, consider this:

I used to bind the name of the workspace this way:
```
set $workspace1 "1: Terminal"
...
assign [class="URxvt"] $workspace1
...
bindsym $mod+1 workspace $workspace1
```

This needs to be changed to:
```
set $workspace1 "1"
...
assign [class="URxvt"] number $workspace1
..
bindsym $mod+1 workspace number $workspace1
```

Note the additional `number` in the command

**Comment by dderjoel** [comment]
Damn.
`assign [class="URxvt"] number $workspace1`
 must be 
`assign [class="URxvt"] workspace number $workspace1`

**Comment by dderjoel** [comment]
Oh, and having checked the classes with `xprop`, the config needs the keys to be lowercase, regardless of what the actual name is.

**Comment by dderjoel** [comment]
Ah, something is still wrong.
concerning the assignment of my URxvt (terminal emulator) to the workspace it works sometimes.

i3 config:
`assign [class="URxvt"] 1`
this maps this window to workspace 1, and the i3-rename script changes the name according to the config to `1: Terminal `. Works as expected.

Opening any next instance of URxvt, it spawns a new workspace called "1" and assigns every instance to that it.

Interestingly, according to the i3 [Documentation](https://i3wm.org/docs/userguide.html#assign_workspace) , 
```
# Assign to the workspace with number 2, regardless of name
assign [class="^URxvt$"] → number 2
``` 
when using the number keyword it gets even worse.

i3 config:
`assign [class="URxvt"] number 1`

will open (at least all instances) to a newly spawned workspace called "number 1". 

Then the i3-renameworkspaces script does rename it and any shortcut (mod+1) will open another workspace called 1, and not focus "number 1"


I almost think that this (at least the second) is an issue purely to i3, not considering the number keyword correctly.

**Comment by mh21** [comment]
Hi dderjoel,

thank you for your bug report, sorry for the delay.

I've added a couple of lines to the readme file and removed the lowercasing of the class and instance names. 

I normally don't use assign rules, and I have an ancient i3. But from https://github.com/i3/i3/commit/eaf7a49e28b7ff8e1820a1b23350647574a0ed5a it sounds as assign+numbered workspaces was added in 4.16. Which version do you use?

Cheers

Michael

**Comment by dderjoel** [comment]
Hi
I am using version 4.16 (2018 - 11 - 04), 
and I am not using assigns anymore either, because its not working solely as I described above and I was not able to figure out a combination which worked. I think it might be some race condition between i3's assignment to the workspace and the i3-renameworkspacescript being run.

However I am still experiencing issues with the script. If I use mod+shit+<3> it will create a new workspace "3" instead of adding the focussed application to "3: urxvt". Resulting in to workspaces ("3" and "3: urxvt") and with pressing Mod + 3 I cannot gain focus on the "3: urxvt".
Of cause this is neither limited to urxvt nor to "3".

my config says  (or see my dotfiles, here on github)
`bindsym $mod+3 workspace number 3`
`bindsym $mod+Shift+3 move container to workspace 3`

I can get out of this by moving the current window to a non existent ws "6" which then creates "6: urxvt" and then focussing "6: urxvt" will remove ws "3" which then leaves me with "3: urxvt" and "6: urxvt"
Or focus "3: uxvt", close the app and then the other "3" will be renamed to "3: uxrxvt".

**Comment by mh21** [comment]
>
> bindsym $mod+Shift+3 move container to workspace 3
>
I think this should be "move container to workspace number 3"

>

**Comment by dderjoel** [comment]
that works. So we can have this in the Readme. Thanks!
