### ISSUE TITLE
 I can't get the instances to work

### ISSUE THREAD

**Issue by mnsanfilippo** [mh21/i3-renameworkspaces#4]
I have this config
{
    "classes": {
        "chromium": "www",
        "xfce4-terminal": "term",
        "gnome-terminal": "term",
        "sublime_text": "subl",
        "okular": "pdf",
        "google-chrome": "www",
        "firefox": "www"        
    },
    "instances": {
        "mail.google.com": "gmail"
    }
}
with this xprop WM_CLASS(STRING) = "mail.google.com", "Chromium"
but the instance of mail.google.com always shows "www" instead of gmail, 
I'm doing it wrong?
Thanks
edit: mail.com.google runs through a bash script to make it "web app"

**Comment by mh21** [comment]
Hi mnsanfilippo,

I think this is an ordering issue. 

In i3-renameworkspaces.pl line 47-49, the script tries to take the first available value from, in that order, the `classes` hash, the `instances` hash and the class name itself. Does it work for you when you swap the order of the hashes in line 47 and 48, i.e.

        my $name = $$config{'instances'}{$instance} || $$config{'classes'}{$class} || $class;

Cheers

Michael

**Comment by mh21** [comment]
Fixed in 6058ac0.
