### ISSUE TITLE
Use of uninitialized value in lc ...i3-renameworkspaces.pl line 51.

### ISSUE THREAD

**Issue by gyula-ny** [mh21/i3-renameworkspaces#8]
Hi,
thanks for the script, it makes i3 bar a whole lot more sense. A tiny problem is that it keeps pumping into the logs the error message:
`Use of uninitialized value in lc at /home/..[path]../i3-renameworkspaces/i3-renameworkspaces.pl line 51.`
(Using perl 5.30.3)
Can this be fixed? (unfortunately, I have no idea about perl).

**Comment by mh21** [comment]
This should be fixed with 9f864a6008d6c3c4815e0910ef7fa645e7be10cf. Could you check whether it works for you?

**Comment by gyula-ny** [comment]
Yes, it does work - thanks a lot!
